export default {
  cs: {
    "menu.home": "/",
    "menu.onlineKatalog": "https://asep.lib.cas.cz/arl-cav/cs/index/",
    "menu.vyhledavac": "/vyhledavac/",
    "vedni_oblast.1": "/vo/oblast/",
    "menu.zvolitUstav": "/zvolit-ustav/",
    "menu.napoveda": "/napoveda/",
    "menu.oDatabazi": "/o-databazi/",
    "menu.search": "/hledej/",
    "oblast.1": "/vo/oblast/1/",
    "oblast.2": "/vo/oblast/2/",
    "oblast.3": "/vo/oblast/3/",
    "vedni_oblast.2": "/vo/porovnani/",
    "vedni_oblast.3": "/vo/sekce/",
    "vedni_oblast.4": "/vo/cela/",
    "vedni_oblast.5": "/vo/prehled/",
    "oddeleni.seznam": "/seznam-oddeleni/",
    "oddeleni.detail": "/oddeleni/",
    "login": "/login/",
    "autor": "/autor/",
  },

  sk: {
  },

  en: {
    "menu.home": "/en/",
    "menu.onlineKatalog": "https://asep.lib.cas.cz/arl-cav/en/search/",
    "menu.vyhledavac": "/en/search-engine/",
    "menu.zvolitUstav": "/en/choose-institute/",
    "vedni_oblast.1": "/en/vo/region/",
    "menu.napoveda": "/en/help/",
    "menu.oDatabazi": "/en/about-database/",
    "menu.search": "/search/",
    "oblast.1": "/en/vo/region/1",
    "oblast.2": "/en/vo/region/2",
    "oblast.3": "/en/vo/region/3",
    "vedni_oblast.2": "/en/vo/comparison/",
    "vedni_oblast.3": "/en/vo/sections/",
    "vedni_oblast.4": "/en/vo/whole/",
    "vedni_oblast.5": "/en/vo/summary/",
    "oddeleni.seznam": "/department-list/",
    "oddeleni.detail": "/department/",
    "login": "/en/login/",
    "autor": "/author/",
  },
};